### ISSUE TITLE
Reports section

### ISSUE THREAD

**Issue by peacog** [National-Forestry-Authority/farmers#36]
Create Reports section with the following reports:

- [x] Farmers - list farmer with all details (farmer details, offer/license and subareas) with export to excel. This report will be used for back up and data sharing. ( Issue #42 )
- [x] Farmers with/without Offer/License details by CFR - filtered by (letter offer date, license number, Block ID allocated, Total area allocated, License start date and License end date). ( Issue #43 )
- [x] Farmers with/without farmer details - filtered by (Farmer type, phone number, postal address and Physical address. ( Issue #44 )
- [x] Farmers entered by data entrants by CFRs - filtered by the data entrants ( Issue #45 )
- [x] Farmers with/without subareas (planted areas) by CFR ( Issue #46 )
- [ ] Performance, Area allocated vs Area planted - filtered by Farmer, CFR and Range. ( Issue #47 )
- [ ] Farmers who have harvested trees by CFR (depends on functionality not yet implemented) ( Issue #48 )
